apiVersion: v1
kind: Pod
metadata:
  name: flux-test
  namespace: default
  labels:
    app: flux-test
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
