apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-oauth2-proxy
  namespace: observability
spec:
  provider: azure
  parameters:
    tenantId: ${AZURE_TENANT_ID}
    clientID: ${ID_GRAFANA_OAUTH2_PROXY}
    keyvaultName: ${KEYVAULT_NAME}
    objects: |
      array:
        - |
          objectName: grafana-oauth2-proxy-cookie-secret
          objectType: secret
  secretObjects:
    - secretName: grafana-oauth2-proxy
      type: Opaque
      data:
        - objectName: grafana-oauth2-proxy-cookie-secret
          key: cookie-secret
