name: Deploy Infra

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  changes:
    runs-on: ubuntu-24.04
    outputs:
      terraform: ${{ steps.filter.outputs.terraform }}
    steps:
      - uses: actions/checkout@v7

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            terraform:
              - 'cloud/**'
              - 'k8s/terraform/**'
              - 'terraform-backend/**'

  terraform-cloud:
    runs-on: ubuntu-24.04
    needs: changes
    if: needs.changes.outputs.terraform == 'true'
    defaults:
      run:
        working-directory: cloud
    steps:
      - uses: actions/checkout@v7

      - uses: azure/login@v3
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.16.1

      - name: Terraform Init
        run: terraform init -reconfigure -upgrade -backend-config=../terraform-backend/main.tfbackend

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

  terraform-k8s:
    runs-on: ubuntu-24.04
    needs: terraform-cloud
    defaults:
      run:
        working-directory: k8s/terraform
    steps:
      - uses: actions/checkout@v7

      - uses: azure/login@v3
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.16.1

      - name: Terraform Init
        run: terraform init -reconfigure -upgrade -backend-config=../../terraform-backend/main.tfbackend

      - name: Terraform Plan
        env:
          TF_VAR_github_app_pem: ${{ secrets.GH_APP_PEM }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        env:
          TF_VAR_github_app_pem: ${{ secrets.GH_APP_PEM }}
        run: terraform apply -auto-approve tfplan
